name: Carrie Eden Smith
favicon: null
layout_spectrum: 0.3306707749143243
typography_spectrum: 0.9140256347600371
title: Carrie Eden Smith
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8124901771079749
  lightness: 0.3513400705996901
  saturation: 0.7686640087049454
  rhythmicContrast: 0.06348718050867319
purpose: []
