name: Carrie Eden Smith
favicon: null
layout_spectrum: 1
typography_spectrum: 0.11032
title: Carrie Eden Smith
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e7d8c5'
    - '#3f2232'
    - '#be725a'
    - '#6d3f38'
    - '#2483a1'
  brandStrength: 1
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
